import 'participant.dart';

/// Represents a review for a specific stopover.
///
/// Every stopover is associated with a list of reviews, each containing
/// a message, the author, and an optional photo.
class Review {
  /// The unique identifier for the review.
  /// This field is nullable because the ID is generated by the database
  /// after the review is first created.
  final int? reviewID;

  /// The main text content of the review.
  /// This field is required to provide the feedback or commentary.
  final String message;

  /// The author of the review.
  /// This is an instance of the [Participant] class, linking the review
  /// to a specific person.
  Participant author;

  /// The foreign key that links this review to its corresponding stopover.
  /// This field is required to associate a review with a specific location.
  final int stopoverId;

  /// The file path for a photo associated with the review.
  /// This can be used to visually complement the text message.
  String photoPath;

  /// Constructs a [Review] instance.
  ///
  /// The [reviewID] is optional and is used to identify existing reviews.
  /// All other fields are required
  /// to create a new, complete review.
  Review({
    this.reviewID,
    required this.author,
    required this.message,
    required this.stopoverId,
    required this.photoPath,
  });
}
